[SD-Jukebox]
MajorVersion=1
MinorVersion=0
Level=032
Edition=0
Setup=SD_MOBILEIMPACT_LE
Company=Panasonic
ProductName=SD-MobileImpact
ProductKey=SD-MobileImpact.exe
RegName=SD-MobileImpact

[SecDevice]
DeviceNum=34
Default=0029

KeyDevice0=SV-AS30/AS3
KeyDevice1=SV-AS10
KeyDevice2=SV-AV50/AV35/AV30
KeyDevice3=SV-SD400V/SD800N
KeyDevice4=SV-SD770V/570V/370V/710/510/310
KeyDevice5=SV-SD750V/350V/700/300
KeyDevice6=SV-SD100V
KeyDevice7=SV-SD90
KeyDevice8=SV-SD80/SD50
KeyDevice9=SV-SD75
KeyDevice10=SV-SD70
KeyDevice11=SC-SX850/SX800/SX450/SX400
KeyDevice12=SC-PM730SD/PM710SD/930DVD/910DVD
KeyDevice13=V603SH/V602SH/V601SH
KeyDevice14=905SH/904SH/903SH/804SH/703SH/703SHf
KeyDevice15=705SH
KeyDevice16=V801SA
KeyDevice17=902SH/802SH/V801SH/V501SH
KeyDevice18=J-SH53/SH52/SH51
KeyDevice19=W43SA/W41SA/W33SA/W32SA/W31SA‡U/W31SA
KeyDevice20=W42H/W41H/W32H
KeyDevice21=W41CA
KeyDevice22=SH903i/SH902iS/SH902i/SH702iD
KeyDevice23=N902iS
KeyDevice24=N902iX HIGH-SPEED
KeyDevice25=N903i
KeyDevice26=P903i/P702iD/P902iS
KeyDevice27=P902i/P702i/P901iS/P701iD
KeyDevice28=P903iTV
KeyDevice29=911SH/910SH/811SH/810SH
KeyDevice30=CN-HDS960TD/HDS940TD/HDS910TD
KeyDevice31=CN-HDS635TD/HDS635RD/HDS635D
KeyDevice32=CN-HDS625TD/HDS625RD/HDS625D
KeyDevice33=Other

[SV-AS30/AS3]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0001

[SV-AS10]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0002

[SV-AV50/AV35/AV30]
CodecFlg=6
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0003

[SV-SD400V/SD800N]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0004

[SV-SD770V/570V/370V/710/510/310]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0005

[SV-SD750V/350V/700/300]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0006

[SV-SD100V]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0007

[SV-SD90]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0008

[SV-SD80/SD50]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0009

[SV-SD75]
CodecFlg=6
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0010

[SV-SD70]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0011

[SC-SX850/SX800/SX450/SX400]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=1
DeviceFlg=1
DeviceID=0012

[SC-PM730SD/PM710SD/930DVD/910DVD]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0013

[V603SH/V602SH/V601SH]
CodecFlg=2
DefaultTypeFlg=1
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0014

[905SH/904SH/903SH/804SH/703SH/703SHf]
CodecFlg=6
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0015

[705SH]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0016

[V801SA]
CodecFlg=6
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0017

[902SH/802SH/V801SH/V501SH]
CodecFlg=2
DefaultTypeFlg=1
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0018

[J-SH53/SH52/SH51]
CodecFlg=2
DefaultTypeFlg=1
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0019

[W43SA/W41SA/W33SA/W32SA/W31SA‡U/W31SA]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0020

[W42H/W41H/W32H]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=1
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0021

[W41CA]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=1
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0022

[SH903i/SH902iS/SH902i/SH702iD]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0023

[N902iS]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0024

[P903i/P702iD/P902iS]
CodecFlg=20
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0025

[P902i/P702i/P901iS/P701iD]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0026

[N902iX HIGH-SPEED]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0027

[N903i]
CodecFlg=20
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0028

[P903iTV]
CodecFlg=20
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=0029

[911SH/910SH/811SH/810SH]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0030

[CN-HDS960TD/HDS940TD/HDS910TD]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0031

[CN-HDS635TD/HDS635RD/HDS635D]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0032

[CN-HDS625TD/HDS625RD/HDS625D]
CodecFlg=4
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=0
PictFlg=0
DeviceFlg=0
DeviceID=0033

[Other]
CodecFlg=7
DefaultTypeFlg=2
DefaultBitrateFlg=0
ImageFlg=1
PictFlg=0
DeviceFlg=0
DeviceID=9999




;CodecFlg            BIT(0)-WMA  BIT(1)-MP3  BIT(2)-AAC  BIT(3)-G726  BIT(4)-SBR
;DefaultTypeFlg      0-WMA       1-MP3       2-AAC 
;DefaultBitrateFlg   0-96kbps    1-128kbps
