;LANG_ENGLISH
[9]
SubLangNum=0
MainURL=http://panasonic.co.jp/pavc/global/cs/soft/index.html

;LANG_FRENCH
[12]
SubLangNum=0
MainURL=http://panasonic.co.jp/pavc/global/cs/soft/index.html

;LANG_GERMAN
[7]
SubLangNum=0
MainURL=http://panasonic.co.jp/pavc/global/cs/soft/index.html

;LANG_JAPANESE
[17]
SubLangNum=0
MainURL=http://panasonic.jp/support/software/sdmi/index.html

;LANG_CHINESE
[4]
SubLangNum=0
MainURL=http://panasonic.co.jp/pavc/global/cs/soft/index.html




